import "@/index.html";
import "@/scss/index.scss";
import "@/components/Navigation/Navigation.js";
import "@/components/Empty-page/Empty-page.js";
import "@/components/Button/Button.js";
import "@/js/change.js"
import "@/js/render.js"
import "@/js/requests/xhr.js"
import "@/js/requests/fetch.js"
import "@/js/requests/axios.js"
