import "@/index.html";
import "@/scss/index.scss";
import "@/components/Navigation/Navigation.js";
import "@/components/Empty-page/Empty-page.js";
import "@/components/Project-item/Project-item.js";
import "@/components/Button/Button.js";
import "@/components/Search/Search.js";
import "@/components/DropDown/DropDown.js";
import "./render.js"
